modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory (26 is current forge version)
license="GNU LESSER GENERAL PUBLIC LICENSE"
[[mods]] #mandatory
modId="wikizoomer" #mandatory
version="1.2.1" #mandatory
displayName="Wiki Zoomer" #mandatory
displayURL="https://github.com/Alex-the-666/WikiZoomer" #optional
logoFile="wikizoomer.png" #optional
credits="" #optional
authors="Alexthe666" #optional
description='''
A mod which adds blocks that allow players to take isometric screenshots of items, blocks and entities.
'''